### ISSUE TITLE
What Spdx Versions Does This Tools-Java  Support

### ISSUE THREAD

**Issue by rakeshsrinivasa** [spdx/tools-java#130]
Hi, 

Is there any documentation where there is list of supporting versions of spdx this repo supports. 
Below are my questions
1. All the samples in this repo are of 2.2 and 2.3 versions. I don't see any older versions samples .  
2.  Does this repo or lib supports parsing older spdx versions like 2.1 or older ?

**Comment by goneall** [comment]
> Is there any documentation where there is list of supporting versions of spdx this repo supports.

It's currently only documented in one of the libraries in the code: https://github.com/spdx/Spdx-Java-Library/blob/master/src/main/java/org/spdx/library/Version.java

Add this to the README would be a good idea.

> Does this repo or lib supports parsing older spdx versions like 2.1 or older ?

Yes - it can read every version since 1.0, although it will only write version 2.0 and up (it will basically convert the 1.0 version to the equivalent 2.0 version). 

> All the samples in this repo are of 2.2 and 2.3 versions. I don't see any older versions samples .

True - Version 2.2 is when we moved the SPDX spec into Github.  It's a bit more difficult to retrieve the prior sample versions.
