### ISSUE TITLE
SpdxConverter changes referenceType of external references

### ISSUE THREAD

**Issue by nicoweidner** [spdx/tools-java#80]
I wrote some test utilities around converting spdx documents between formats and noticed some weird behavior:
- I used the examples from https://github.com/spdx/spdx-spec/tree/development/v2.3.1/examples
- The `.xml`, `.yaml` and `.rdf.xml` examples contain a long version of a purl referenceType of an externalRef, e.g.
```
    referenceType: "http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#purl"
``` 
- When converting one of these files to `.xls`, `.xlsx` or `.spdx`, this long version is lost and replaced by `purl`

My suspicion is that this is caused by [spreadsheet-store](https://github.com/spdx/spdx-java-spreadsheet-store) and [tagvalue-store](https://github.com/spdx/spdx-java-tagvalue-store). Before opening issues there, I wanted to clarify whether this is indeed a bug or expected behavior.
(Spoiler: Such behavior makes comparisons between different formats rather nasty :sweat_smile: )

**Comment by goneall** [comment]
@nicoweidner Definitely some issue(s) here.

Since the purl reference type is "pre-defined" in the spec, I think it is OK for the spreadsheet and tag/value to have the short form.  I would expect XML, YAML, and JSON would also have the short form, however. The long form above also looks incorrect, the referenceType should be `http://spdx.org/rdf/references/purl`.  If you convert from a document which incorrectly translates `http://spdx.org/rdf/references/purl` to `http://spdx.org/spdxdocs/spdx-example-444504E0-4F89-41D3-9A0C-0305E82C3301#purl` any docs translated from that will probably retain the long form since it won't recognize it as a standard reference type.  I'm hoping there's just one bug causing this ;)

**Comment by nicoweidner** [comment]
Hm... I can't tell which root causes are at play here now :sweat_smile: 

From what you said, I conclude that something is wrong with the examples, specifically referenceType in [the rdf.xml example](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXRdfExample-v2.3.spdx.rdf.xml#L1525), [the xml example](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXXMLExample-v2.3.spdx.xml#L270) and [the yaml example](https://github.com/spdx/spdx-spec/blob/development/v2.3.1/examples/SPDXYAMLExample-2.3.spdx.yaml#L235) from the spdx-spec repo. I created https://github.com/spdx/spdx-spec/issues/799 in the spdx-spec repo.

Next, about the conversion: I should have mentioned that I used [SpdxConverter.convert](https://github.com/spdx/tools-java/blob/5ab3b3f550b4cd05d04173a9e76305f29de14ceb/src/main/java/org/spdx/tools/SpdxConverter.java#L111) from tools-java to do the conversion. For the combinations of input and output format mentioned above, it retains only `purl`.

I poked around in the two stores a bit. I suspect that [this section of the spreadsheet store](https://github.com/spdx/spdx-java-spreadsheet-store/blob/cda724ac650a9442dff195908d39573c2892a327/src/main/java/org/spdx/spreadsheetstore/ExternalRefsSheet.java#L226-L228) and [this section of the tagvaluestore](https://github.com/spdx/spdx-java-tagvalue-store/blob/27174afb1b057555f2859c6c4d22a182a1d9186a/src/main/java/org/spdx/tag/CommonCode.java#L718-L720) are responsible for removing the documentUri part and leaving only `purl`.

As for what the desired state should be: I have no idea right now :sweat_smile: . In terms of comparison, I realized that the java library also [ignores referenceType in the equivalent method](https://github.com/spdx/Spdx-Java-Library/blob/06ffee5e3754400a36dbb2f652d814c92e228e87/src/main/java/org/spdx/library/model/ExternalRef.java#L329), so I just ignore it in comparisons as well.

**Comment by goneall** [comment]
@nicoweidner Thanks for the additional research.  I believe most of this is expected behavior.

I went back and looked at the above referenced spreadsheet store and tag value store code and the shortening of the types are correct in that we always remove any URI prefixes for the document namespace when converting from RDF - this would include the `referenceType`.

The examples are clearly incorrect IMO - probably because they were not updated correctly after the 2.3 changes.  I just created PR to fix.

I just ran the converter from the JSON example (which is correct) and it produced the correct result - so I don't think there is an issue with the libraries or conversion utility.

To summarize the expected behavior:
- For [defined external repository identifier](https://spdx.github.io/spdx-spec/v2.3/external-repository-identifiers/):
  - RDF formats prefix the identifier with the standard SPDX RDF prefix "https://spdx.org/rdf/terms/"
  - All other formats only use just the identifier
- For repository identifiers defined within the SPDX document and not defined by SPDX:
  - RDF formats prefix the identifier with the document namespace
  - Tag/Value and Spreadsheet does not include the namespace prefix
  - the XML, YAML, and JSON formats do not have a documented expected behavior for this - something we should probably address (in general, these formats are under-documented in the spec)

**Comment by nicoweidner** [comment]
@goneall Thanks for the detailed explanation! I agree that it looks like only some examples were wrong. It's unfortunate that such details are so hard (or in some cases impossible) to learn from just the spec.

I'll close this, since there is not actually an issue with the java tools.
