### ISSUE TITLE
RDF Turtle format generates error 

### ISSUE THREAD

**Issue by zvr** [spdx/tools-java#88]
On v1.1.2, the tools cannot convert to a Turtle formatted file.

> $ java -jar ./tools-java-1.1.2/tools-java-1.1.2-jar-with-dependencies.jar Convert ./spdx-spec/examples/SPDXRdfExample-v2.3.spdx.rdf.xml /tmp/foo.rdf.ttl
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> 16:24:26.801 [main] ERROR org.apache.jena.util.JenaXMLInput - Problem setting StAX property - name: "http://javax.xml.xmlconstants/property/accessExternalDTD" - value: "" - error: Unrecognized property 'http://javax.xml.XMLConstants/property/accessExternalDTD'
> Error converting: Error converting SPDX file: class org.apache.jena.shared.NoWriterForLangException Writer not found: TURTLE

**Comment by goneall** [comment]
@zvr This was likely caused by an update to the Jena libraries in the latest release to resolve a potential security vulnerability.

I was able to duplicate the first error `16:24:26.801 [main] ERROR org.apache.jena.util.JenaXMLInput - Problem setting StAX property - name: "http://javax.xml.xmlconstants/property/accessExternalDTD" - value: "" - error: Unrecognized property 'http://javax.xml.xmlconstants/property/accessExternalDTD'`  however, the second error on no writer found didn't occur and it was able to produce the TURTLE output.

I didn't find much googling the first error - here's one stack overflow article: https://stackoverflow.com/questions/58374278/org-xml-sax-saxnotrecognizedexception-property-http-javax-xml-xmlconstants-p

I don't know if it is related to what we're seeing - I'll continue to investigate.

**Comment by goneall** [comment]
Update - I was able to duplicate both problems when running from the command line.  The second error doesn't happen in the development environment.  Must be something to do with how the jar-with-dependencies is built.

**Comment by goneall** [comment]
Found this which seems to be related: https://stackoverflow.com/questions/58562397/org-apache-jena-shared-noreaderforlangexception-reader-not-found-nt
